# Generated by Django 2.2.1 on 2019-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionCacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dep', models.IntegerField()),
                ('departamento', models.CharField(max_length=50)),
                ('cod_mun', models.IntegerField()),
                ('municipio', models.CharField(max_length=50)),
                ('grupo_cultivo', models.CharField(max_length=50)),
                ('sub_grupo_cultivo', models.CharField(max_length=50)),
                ('cultivo', models.CharField(max_length=50)),
                ('sistema_productivo', models.CharField(max_length=50)),
                ('codigo_cultivo', models.IntegerField()),
                ('nombre_cientifico', models.CharField(max_length=50)),
                ('periodo', models.IntegerField()),
                ('area_sembrada', models.FloatField()),
                ('area_cosechada', models.FloatField()),
                ('produccion', models.FloatField()),
                ('rendimiento', models.FloatField()),
                ('estado_produccion', models.CharField(max_length=50)),
            ],
        ),
    ]
