# Generated by Django 2.2.1 on 2019-06-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0002_produccioncacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Integrantes',
            new_name='Estudiantes',
        ),
    ]
