# Generated by Django 2.2.1 on 2019-06-16 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0003_auto_20190611_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produccion_municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_municipio', models.IntegerField()),
                ('municipio', models.CharField(max_length=50)),
                ('cultivo', models.CharField(max_length=50)),
                ('codigo_cultivo', models.IntegerField()),
                ('nombre_cientifico', models.CharField(max_length=50)),
                ('periodo', models.IntegerField()),
                ('area_sembrada', models.FloatField()),
                ('area_cosechada', models.FloatField()),
                ('produccion', models.FloatField()),
                ('rendimiento', models.FloatField()),
                ('estado_produccion', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prueba.Departamentos')),
            ],
        ),
    ]
