# Generated by Django 2.2.1 on 2019-07-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0005_albumimagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
