# Generated by Django 2.2.1 on 2019-06-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('area', models.FloatField()),
                ('cantidad_peces', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piscicultura.Pozo')),
            ],
        ),
        migrations.CreateModel(
            name='PH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piscicultura.Pozo')),
            ],
        ),
        migrations.CreateModel(
            name='O2disuelto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('pozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='piscicultura.Pozo')),
            ],
        ),
    ]
